### ISSUE TITLE
Clarity around logFC for gene_stats

### ISSUE THREAD

**Issue by AMChalkie** [LiuzLab/CB2#9]
Hi,

1) For sgRNA the code is
log2(est$cpm_b + 1) - log2(est$cpm_a + 1)
2) And for gene level:
mean(logFC) of all sgRNA in that gene.

This has the unfortunate effect that if you try and re-calculate the logFC from the cpm values in the sheet level data, you get a difference. It is worth being explicit about this, or having multiple CPMs (although that would create confusion). 

Best wishes
Alistair

**Comment by hyunhwaj** [comment]
Thanks for the report, and there have been some changes to clarify the logFC.

First, the `logFC_level` argument has been added. The default value of the argument is set to "sgRNA" (i.e. it will be set to "sgRNA" if there is no value is assigned) because to make the default mode produces the same result what the previous version had produced. In the later version, it is possible to change the default value.

https://github.com/LiuzLab/CB2/blob/5aeef4b5efd4c7ce82f9b1c11d5159d075275c97/man/measure_gene_stats.Rd#L12

Second, in the documentation, I have added the detailed description as follows:
 https://github.com/LiuzLab/CB2/blob/5aeef4b5efd4c7ce82f9b1c11d5159d075275c97/man/measure_gene_stats.Rd#L21

To test the latest version, please use `devtools` to install. I will submit it to cran.

Thanks,

Hyun-Hwan Jeong

**Comment by AMChalkie** [comment]
Thanks, much appreciated.

**Comment by hyunhwaj** [comment]
It is now available in cran.
